global:
  scrape_interval: 15s # 默认每15秒抓取一次目标。

  # 在与外部系统（如联邦、远程存储、Alertmanager）通信时，为每个时序数据或告警附加这些标签。
  external_labels:
    monitor: "railway-prom"

# 抓取配置：包含一个端点，抓取Prometheus自身。
scrape_configs:
  # job_name作为标签`job=<job_name>`添加到抓取的所有时序数据中。
  - job_name: "prometheus"

    # 覆盖全局默认值，此job每5秒抓取一次目标。
    scrape_interval: 5s

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "whale_pushgateway"
    scrape_interval: 5s
    static_configs:
      - targets: ["163.61.102.47:30091"]

  # - job_name: 'postgres'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9187']

  # - job_name: 'mysql'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9104']
